import { SET_TOURS_MORE_PAGES_SHOW, SET_TOURS_PAGE} from './ActionTours';

const initialState = {
    toursPage: 1,
    toursShowPages: 1,
    tours: [
        {
            country: "Imperii Romani Orientalis",
            tours: [
                {
                    rating: 3.1,
                    comments: 102,
                    id: 0,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 1,
                    price: 350, 
                },
                {
                    rating: 3.2,
                    comments: 100,
                    id: 1,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info Konstantinopolis info ",
                     "Antioch info Antioch info Antioch info Antioch info Antioch info Antioch info Antioch info Antioch info Antioch info Antioch info Antioch info Antioch info Antioch info ",
                     "Alexandria Egyptian info Alexandria Egyptian info Alexandria Egyptian info Alexandria Egyptian info Alexandria Egyptian info Alexandria Egyptian info Alexandria Egyptian info Alexandria Egyptian info Alexandria Egyptian info Alexandria Egyptian info Alexandria Egyptian info Alexandria Egyptian info Alexandria Egyptian info Alexandria Egyptian info Alexandria Egyptian info Alexandria Egyptian info ",
                     "Carthage info Carthage info Carthage info Carthage info Carthage info Carthage info Carthage info Carthage info Carthage info Carthage info Carthage info Carthage info Carthage info ",
                     "Roma info ", ["Перемещение на комфортабельном дромоне","Предоставление гидов, говорящих на любом языке Средиземноморья","Обширная экскурсия по столице Империи"],["Посещение любых портов Средиземноморья в пути по вашему выбору","Профессиональная охрана"]],
                    passengersAvailable: 2,
                    price: 323, 
                },
                {
                    rating: 3.3,
                    comments: 92,
                    id: 2,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 3,
                    price: 256, 
                },
                {
                    rating: 3.4,
                    comments: 18,
                    id: 3,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 4,
                    price: 567, 
                },
                {
                    rating: 3.5,
                    comments: 78,
                    id: 4,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 5,
                    price: 342, 
                },
                {
                    rating: 3.6,
                    comments: 58,
                    id: 5,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 6,
                    price: 155, 
                },
                {
                    rating: 3.7,
                    comments: 78,
                    id: 6,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 7,
                    price: 62, 
                },
                {
                    rating: 3.8,
                    comments: 38,
                    id: 7,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 8,
                    price: 432, 
                },
                {
                    rating: 3.8,
                    comments: 83,
                    id: 8,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 9,
                    price: 254, 
                },
                {
                    rating: 2.1,
                    comments: 112,
                    id: 9,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 10,
                    price: 841, 
                },
                {
                    rating: 2.2,
                    comments: 112,
                    id: 10,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 1,
                    price: 300, 
                },
                {
                    rating: 2.3,
                    comments: 112,
                    id: 11,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 2,
                    price: 300, 
                },
                {
                    rating: 2.4,
                    comments: 11,
                    id: 12,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 3,
                    price: 300, 
                },
                {
                    rating: 2.5,
                    comments: 15,
                    id: 13,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 4,
                    price: 300, 
                },
                {
                    rating: 2.6,
                    comments: 112,
                    id: 14,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable:5,
                    price: 300, 
                },
                {
                    rating: 2.7,
                    comments: 112,
                    id: 15,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 6,
                    price: 300, 
                },
                {
                    rating: 2.8,
                    comments: 112,
                    id: 16,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 7,
                    price: 300, 
                },
                {
                    rating: 3.1,
                    comments: 112,
                    id: 7,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 8,
                    price: 300, 
                },
                {
                    rating: 3.1,
                    comments: 112,
                    id: 18,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 9,
                    price: 300, 
                },
                {
                    rating: 3.1,
                    comments: 112,
                    id: 19,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 11,
                    price: 300, 
                },
                {
                    rating: 3.1,
                    comments: 112,
                    id: 20,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 12,
                    price: 300, 
                },
                {
                    rating: 3.1,
                    comments: 112,
                    id:21,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 13,
                    price: 300, 
                },
                {
                    rating: 3.1,
                    comments: 112,
                    id: 22,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 14,
                    price: 300, 
                },
                {
                    rating: 3.1,
                    comments: 112,
                    id: 23,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 15,
                    price: 300, 
                },
                {
                    rating: 3.1,
                    comments: 112,
                    id: 24,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 16,
                    price: 300, 
                },
                {
                    rating: 3.1,
                    comments: 112,
                    id: 25,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 17,
                    price: 300, 
                },
                {
                    rating: 3.1,
                    comments: 112,
                    id: 26,
                    departureDate: new Date(Date.now()),
                    info: "Новый тур по самым крупным центрам империи, олицетворяющим её богатство и мощь. Перемещение организовано на комфортабельном дромоне. По пути возможен заход в любой порт Средиземноморья. Каждый посещённый город оставит о себе незабываемые впечатления. В каждом из них для вас будет предоставлены верховые животные или паланкин для удобства перемещения по городу. Опытные гиды и тренированная охрана будут в вашем распоряжении в любое время дня и ночи.",
                    places: ["Konstantinopolis", "Antioch", "Alexandria Egyptian", "Carthage", "Roma"],
                    placesInfo: ["Konstantinopolis info", "Antioch info", "Alexandria Egyptian info", "Carthage info", "Roma info", ["AAA","BBB","CCC"],["AA","BB"]],
                    passengersAvailable: 18,
                    price: 300, 
                },
                


            ]
        }
    ]
}

export const ToursReduser = (state = initialState, action)=>{
    switch (action.type){
        case SET_TOURS_MORE_PAGES_SHOW:{
            let newState={...state};
            newState.toursShowPages=newState.toursShowPages+1;
            newState.toursPage=newState.toursPage+1;
            return newState;
        }
        case SET_TOURS_PAGE: {
            let newState = {...state};
            newState.toursPage=action.toursPage;
            newState.toursShowPages=1;
            return newState;
        }
        default: return state;
    }
    
}